# Testing
## Varför behövs dessa
### Numpy

- Numpy är skrivet i C
- Python är ett intterpreterat språk, därför långsamt
- C är ett kompilerat språk, därför snabbt

In [22]:
import numpy as np
print("Hola")


Hola


In [ ]:
arr = np.array([1, 2, 3])
arr

Numpy arrayer kan bara innehålla en datatyp

In [ ]:
a_list = [1, 2, 3]
a_list = [1 , 2, "3"]
print(a_list)
# np_arr = np.array(a_list, dtype=np.int8)
np_arr = np.array(a_list)
np_arr

Numpy arrayer kan vara flerdimensionella

In [ ]:
one_array = np.ones((3,3), dtype=np.int8)
one_array = one_array.reshape(9, 1)
one_array

In [37]:
arr = np.ones((12,12))
arr[0] = 0
arr[:1, 1:3]

array([[0., 0.]])

In [57]:
# arr = np.array([[1, 2, 3], [4, 5, 6]])
arr = np.arange(1, 7).reshape(2,3)
print(arr)
print(arr[1].prod())
print(arr[1].max())
print(arr[0].min())
print(arr[1].min())
print(arr[0])
np.pi




[[1 2 3]
 [4 5 6]]
120
6
1
4
[1 2 3]


3.141592653589793